### ISSUE TITLE
 The getter 'button' isn't defined for the type 'TextTheme'.

### ISSUE THREAD

**Issue by mr-gami001** [bluemix/Gradient-Widgets#26]
/C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.dev/gradient_widgets-0.6.0/lib/src/gradient_widget.dart:104:73: Error: The getter 'button' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'button'.
    final TextStyle textStyleCopy = widget.textStyle ?? theme.textTheme.button!.copyWith(color: Colors.white);

![Capture](https://github.com/bluemix/Gradient-Widgets/assets/85818705/5c787240-08c7-4885-815f-358b8b10f47e)

**Comment by gulmensedat** [comment]
I updated the package, you can use my github repo, if you still get errors, let me know and I will fix and update the relevant part.

```
gradient_widgets:
    git:
      url: https://github.com/gulmensedat/Gradient-Widgets.git
      ref: master
```
